# Hexo Configuration | Setelan Hexo
## Docs: https://hexo.io/docs/configuration.html | Dokumen: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/ | Sumber: https://github.com/hexojs/hexo/

## Site | Situs
title: Mughni Mind
subtitle: Personal Blog
description: Bekerja Keras Buat Berusaha Keras
author: mughnimind
language: id
timezone: Asia/Jakarta

## URL | URL
### If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/' | Jika situs Anda terletak dalam sub-direktori, setel url sebagai berikut 'http://situsanda.com/child' dan root serupa '/child/'
url: https://mughnimind.github.io/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

## Directory | Direktori
source_dir: source
public_dir: public
tag_dir: Tagar
archive_dir: Arsip
category_dir: Kategori
code_dir: downloads/code
i18n_dir: :lang
skip_render:

## Writing | Penulisan
new_post_name: :title.md # File name of new posts | Nama berkas postingan
default_layout: post
titlecase: false # Transform title into titlecase | Ubah judul ke titlecase
external_link: true # Open external links in new tab | Buka tautan eksternal pada jendela baru
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: false
  line_number: false
  auto_detect: false
  tab_replace:

## Category & Tag | Kategori & Tagar
default_category: uncategorized
category_map:
tag_map:

## Date / Time format | Tanggal / Format waktu
### Hexo uses Moment.js to parse and display date | Hexo memakai Momemt.js untuk memproses dan menampilkan tanggal
### You can customize the date format as defined in | Anda dapat menyesuaikan format penanggalan sesuai dengan ketentuan yang terdapat di
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

## Pagination | Pembagian Halaman
### Set per_page to 0 to disable pagination | Setel per_page dengan nilai 0 untuk menonaktifkan pembagian halaman
per_page: 10
pagination_dir: page

## Extensions | Ekstensi
### Plugins: https://hexo.io/plugins/ | Pengaya: https://hexo.io/plugins/
### Themes: https://hexo.io/themes/ | Tema: https://hexo.io/themes/
theme: material
search:
  path: search.xml
  field: all
prism_plugin:
  mode: 'preprocess'
  theme: 'default'
marked:
  gfm: true
  pedantic: false
  sanitize: false
  tables: true
  breaks: false
  smartLists: true
  smartypants: true
  modifyAnchors: ''
  autolink: true

## Deployment | Publikasi
### Docs: https://hexo.io/docs/deployment.html | Dokumen: https://hexo.io/docs/deployment.html
deploy:
  - type: git
    repo: git@github.com:mughnimind/mughnimind.github.io.git
    branch: master
  - type: git
    repo: git@github.com:mughnimind/mughnimind.github.io.git
    branch: aset
    extend_dirs: /
    ignore_hidden: false
    ignore_pattern:
        public: .
